/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackhuang.hellominecraftlauncher.plugin.mainpanels;

import com.google.gson.Gson;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import org.jackhuang.hellominecraftlauncher.apis.DoneListener;
import org.jackhuang.hellominecraftlauncher.apis.DownloadWindow;
import org.jackhuang.hellominecraftlauncher.apis.utils.Utils;
import org.jackhuang.hellominecraftlauncher.apis.version.MinecraftVersion;
import org.jackhuang.hellominecraftlauncher.download.URLGetThread;
import org.jackhuang.hellominecraftlauncher.loaders.MinecraftVersions;
import org.jackhuang.hellominecraftlauncher.loaders.MinecraftVersionsLoader;
import org.jackhuang.hellominecraftlauncher.plugin.HMCLPlugin;
import org.jackhuang.hellominecraftlauncher.utilities.C;

/**
 *
 * @author hyh
 */
public class GameDownloadPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameDownloadPanel
     */
    public GameDownloadPanel() {
        initComponents();
        
        setName(C.I18N.getString("GameDownload"));
        String[] titleA = new String[]{C.I18N.getString("Version"), C.I18N.getString("Time"), C.I18N.getString("ReleaseTime"), C.I18N.getString("Type")};
        Class[] typesA = new Class[]{String.class,String.class,String.class,String.class};
        boolean[] canEditA = new boolean[]{false,false,false,false};
        lstDownloads.setModel(Utils.makeDefaultTableModel(titleA, typesA, canEditA));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGameDownloads = new javax.swing.JPanel();
        btnDownload = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDownloads = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jackhuang/hellominecraftlauncher/I18N"); // NOI18N
        btnDownload.setText(bundle.getString("下载")); // NOI18N
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        lstDownloads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "版本", "发布时间", "释放时间", "类型"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lstDownloads.setToolTipText("");
        jScrollPane2.setViewportView(lstDownloads);

        btnRefresh.setText(bundle.getString("刷新")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGameDownloadsLayout = new javax.swing.GroupLayout(pnlGameDownloads);
        pnlGameDownloads.setLayout(pnlGameDownloadsLayout);
        pnlGameDownloadsLayout.setHorizontalGroup(
            pnlGameDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameDownloadsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGameDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDownload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlGameDownloadsLayout.setVerticalGroup(
            pnlGameDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameDownloadsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGameDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGameDownloadsLayout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownload))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGameDownloads, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGameDownloads, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        downloadMinecraft(HMCLPlugin.env.getSourceType());
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshDownloads(HMCLPlugin.env.getSourceType());
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void refreshDownloads(int index) {
        clearListDownloads();
        URLGetThread thread = new URLGetThread(C.URL_VERSIONLIST[index], "utf-8");
        thread.addListener(new RefreshDownloadsDone());
        thread.start();
    }

    void clearListDownloads() {
        DefaultTableModel model = (DefaultTableModel) lstDownloads.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        lstDownloads.updateUI();
    }
    
    void downloadMinecraft(int index) {
        String id = (String) lstDownloads.getModel().getValueAt(lstDownloads.getSelectedRow(), 0);
        String vurl = C.URL_VERSIONS[index] + id + "/";
        String vpath = HMCLPlugin.env.getDefaultGameDir() + File.separator + "versions" + File.separator + id + File.separator;
        String mvt = vpath + id + ".json";
        String mvj = vpath + id + ".jar";
        new File(vpath).mkdirs();
        new File(mvt).delete();
        new File(mvj).delete();

        /*DownloadAllThread dat = new DownloadAllThread(new ProgressListener(id));
        dat.addDownloadURL("", vurl + id + ".json", vpath + id + ".json");
        dat.addDownloadURL("", vurl + id + ".jar", vpath + id + ".jar");
        dat.start();*/
        DownloadWindow dw = new DownloadWindow();
        dw.addDownloadURL(id + ".json", vurl + id + ".json", mvt);
        dw.addDownloadURL(id + ".jar", vurl + id + ".jar", mvj);
        dw.setVisible(true);
        if(dw.isDownloadSuccessfully()) {
            String aurl = C.URL_INDEXES[index];
            String apath = HMCLPlugin.env.getDefaultGameDir() + File.separator + "assets" + File.separator + "indexes" + File.separator;

            Gson gson = new Gson();
            MinecraftVersion mv = gson.fromJson(Utils.readToEnd(new File(mvt)), MinecraftVersion.class);

            new File(apath).mkdirs();
            new File(apath + mv.assets + ".json").delete();
            dw = new DownloadWindow();
            dw.addDownloadURL(mv.assets + ".json", aurl + mv.assets + ".json", apath + mv.assets + ".json");
            dw.setVisible(true);
        }
    }

    class RefreshDownloadsDone implements DoneListener<String, Object> {

        @Override
        public void onDone(String result, Object value2) {
            javax.swing.JTable table = lstDownloads;
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            MinecraftVersionsLoader loader = new MinecraftVersionsLoader(result);
            MinecraftVersions v = loader.getVersions();
            for (MinecraftVersion ver : v.versions) {
                String[] line = new String[4];
                line[0] = ver.id;
                line[1] = ver.releaseTime;
                line[2] = ver.time;
                line[3] = ver.type;
                model.addRow(line);
            }

        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lstDownloads;
    private javax.swing.JPanel pnlGameDownloads;
    // End of variables declaration//GEN-END:variables
}
