pipeline {
    agent any

    environment {
        HMCL_CI = '1'
        VERSION_TYPE = 'stable'
        BUILD_NUMBER_OFFSET = '0'
        // MICROSOFT_AUTH_ID = credentials('microsoft_auth_id')
        // MICROSOFT_AUTH_SECRET = credentials('microsoft_auth_secret')
        // CURSEFORGE_API_KEY = credentials('curseforge_api_key')
        // HMCL_SIGNATURE_KEY = credentials('hmcl_signature_key')
    }

    stages {
        stage('Build') {
            steps {
                sh './gradlew clean build --stacktrace'
                archiveArtifacts artifacts: 'HMCL/build/libs/*'
            }
        }
    }
}