name: Bug Feedback
description: 
  反馈一个 HMCL 错误。
  为了提高反馈效率，请优先在 KOOK、赞助频道或者 Discord 频道中反馈。若确认是 HMCL 问题，请发布 issue。
title: "[Bug] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        提交前请确认：
        * 该问题确实是 **HMCL 的错误**，而**不是 Minecraft 非正常退出**，如果你的 Minecraft 非正常退出，请前往 [KOOK 频道](https://kook.top/Kx7n3t) 或 [Discord 频道](https://discord.gg/jVvC7HfM6U)中反馈信息。
        * 你的启动器版本是**最新的快照版本**，可以前往 [Github Action](https://github.com/huanghongxun/HMCL/actions?page=2&query=branch%3Ajavafx+event%3Apush+workflow%3A%22Java+CI%22++) 或 [KOOK](https://kook.top/Kx7n3t) 下载最新快照版本。
    
        如果你的问题并不属于上述两类，你可以选取另一种 Issue 类型，或者前往 [KOOK 频道](https://kook.top/Kx7n3t) 或 [Discord 频道](https://discord.gg/jVvC7HfM6U)中反馈信息。
        如果你希望在 QQ 群中反馈问题，请[赞助 HMCL](https://hmcl.huangyuhui.net/api/redirect/sponsor) 后申请加入群聊，也请将下面的信息表填好直接发在群中，加快我们的沟通速度。
  - type: input
    id: platform
    attributes:
      label: 平台 Platform 
      description: 请输入您遇到 BUG 的平台。 Please enter the platform on which you encountered the bug. 
      placeholder: e.g. Windows 11
    validations:
      required: true
  - type: textarea
    id: bug-report
    attributes:
      label: 问题描述 Problem Description
      description: 请尽可能地详细描述你所遇到的问题，并描述如何重新触发这个问题。 Please describe the problem you met in as much detail as possible. Besides, please describe how to trigger this problem again.
    validations:
      required: true
  - type: textarea
    id: hmcl-crash-report-or-logs
    attributes:
      label: 启动器崩溃报告 Launcher Crash Report / 启动器日志文件 Launcher Log File
      description: |
        如果您的启动器崩溃了，请将崩溃报告填入（或将文件拖入）下方。
        如果您的启动器没有崩溃，请在遇到问题后不要退出启动器，在启动器的【设置】>【通用】>【调试】一栏中点击“导出启动器日志”，并将导出的日志拖到下方的输入栏中。 
        
        If your launcher crashes, please fill it in (or drag the file in) below.
        If your launcher doesn't crash, please DO NOT EXIT your launcher, click "Export Launcher Log" in the [Settings] > [General] > [Debug] column of the launcher, and drag the exported log to the input field below.
