name: Feature Request
description: Suggest a new feature or enhancement for HMCL.
title: "[Feature] "
labels: enhancement
body:
- type: markdown
  attributes:
    value: Please make sure that no duplicate issues have already been submitted.
- type: textarea
  id: summary
  attributes:
    label: Summary
    description: Please describe the new feature.
  validations:
    required: true
- type: textarea
  id: reason
  attributes:
    label: Reason
    description: Please describe why you want to add the feature or enhancement to HMCL.
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: Describe implementation details or suggestions here. (Optional)
