/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackhuang.hellominecraftlauncher.plugin.editpanels;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import org.jackhuang.hellominecraftlauncher.apis.utils.MessageBox;
import org.jackhuang.hellominecraftlauncher.apis.utils.Utils;
import org.jackhuang.hellominecraftlauncher.plugin.HMCLPlugin;
import org.jackhuang.hellominecraftlauncher.utilities.C;
import org.jackhuang.hellominecraftlauncher.utilities.FolderOpener;

/**
 *
 * @author hyh
 */
public class TexturepackEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form TexturepackEditPanel
     */
    public TexturepackEditPanel() {
        initComponents();
        
        setName(C.I18N.getString("TexturepackEditor"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstResourcePacks = new javax.swing.JList();
        btnAddResourcePack = new javax.swing.JButton();
        btnDeleteResourcePack = new javax.swing.JButton();
        btnManageResourcePack = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnAddTexturePack = new javax.swing.JButton();
        btnDeleteTexturePack = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstTexturePacks = new javax.swing.JList();
        btnManageTexturePacks = new javax.swing.JButton();

        setName(""); // NOI18N

        jScrollPane5.setViewportView(lstResourcePacks);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jackhuang/hellominecraftlauncher/I18N"); // NOI18N
        btnAddResourcePack.setText(bundle.getString("增加")); // NOI18N
        btnAddResourcePack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResourcePackActionPerformed(evt);
            }
        });

        btnDeleteResourcePack.setText(bundle.getString("删除")); // NOI18N
        btnDeleteResourcePack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteResourcePackActionPerformed(evt);
            }
        });

        btnManageResourcePack.setText(bundle.getString("管理")); // NOI18N
        btnManageResourcePack.setToolTipText("打开资源管理器");
        btnManageResourcePack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageResourcePackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddResourcePack, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDeleteResourcePack, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnManageResourcePack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnManageResourcePack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddResourcePack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteResourcePack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab(bundle.getString("1.6AndAbove"), jPanel9); // NOI18N

        btnAddTexturePack.setText(bundle.getString("增加")); // NOI18N
        btnAddTexturePack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTexturePackActionPerformed(evt);
            }
        });

        btnDeleteTexturePack.setText(bundle.getString("删除")); // NOI18N
        btnDeleteTexturePack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTexturePackActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(lstTexturePacks);

        btnManageTexturePacks.setText(bundle.getString("管理")); // NOI18N
        btnManageTexturePacks.setToolTipText("打开资源管理器");
        btnManageTexturePacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTexturePacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddTexturePack, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDeleteTexturePack, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnManageTexturePacks, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnManageTexturePacks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddTexturePack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteTexturePack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab(bundle.getString("1.5AndBelow"), jPanel10); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddResourcePackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddResourcePackActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle(C.I18N.getString("选择资源包"));
        fc.setMultiSelectionEnabled(false);
        fc.showOpenDialog(this);
        try {
            String path = fc.getSelectedFile().getCanonicalPath();
            lstResourcePacksModel.addElement(path);
        } catch (IOException e) {
            MessageBox.Show(C.I18N.getString("添加失败"));
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddResourcePackActionPerformed

    private void btnDeleteResourcePackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteResourcePackActionPerformed
        String selectedName = (String) lstResourcePacks.getSelectedValue();
        lstResourcePacksModel.removeElementAt(lstResourcePacks.getSelectedIndex());

        String path = getGameDir();
        path += "resourcepacks";
        if (path == null) {
            MessageBox.Show(C.I18N.getString("删除失败"));
            return;
        }
        File newf = new File(path + File.separator + selectedName);
        newf.delete();
    }//GEN-LAST:event_btnDeleteResourcePackActionPerformed

    private void btnManageResourcePackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageResourcePackActionPerformed
        FolderOpener.openResourcePacks(getGameDir());
    }//GEN-LAST:event_btnManageResourcePackActionPerformed

    private void btnAddTexturePackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTexturePackActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle(C.I18N.getString("选择材质包"));
        fc.setMultiSelectionEnabled(false);
        fc.showOpenDialog(this);
        try {
            String path = fc.getSelectedFile().getCanonicalPath();
            lstTexturePacksModel.addElement(path);
        } catch (IOException e) {
            MessageBox.Show(C.I18N.getString("添加失败"));
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddTexturePackActionPerformed

    private void btnDeleteTexturePackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTexturePackActionPerformed
        String selectedName = (String) lstTexturePacks.getSelectedValue();
        lstTexturePacksModel.removeElementAt(lstTexturePacks.getSelectedIndex());

        String path = getGameDir();
        path += "texturepacks";
        if (path == null) {
            MessageBox.Show(C.I18N.getString("删除失败"));
            return;
        }
        File newf = new File(path + File.separator + selectedName);
        newf.delete();
    }//GEN-LAST:event_btnDeleteTexturePackActionPerformed

    private void btnManageTexturePacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTexturePacksActionPerformed
        FolderOpener.openTextutrePacks(getGameDir());
    }//GEN-LAST:event_btnManageTexturePacksActionPerformed

    private String getGameDir() {
        return Utils.getGameDir(HMCLPlugin.env.getVersion(), HMCLPlugin.env.getDefaultGameDir());
    }
    
    public void loadPacks() {
        ArrayList<String> sl;
        String path = getGameDir();
        sl = Utils.findAllFile(new File(path + "resourcepacks"));
        lstResourcePacksModel.clear();
        for (String s : sl) {
            lstResourcePacksModel.addElement(s);
        }
        lstResourcePacks.setModel(lstResourcePacksModel);
        sl = Utils.findAllFile(new File(path + "texturepacks"));
        for (String s : sl) {
            lstTexturePacksModel.addElement(s);
        }
        lstTexturePacks.setModel(lstTexturePacksModel);
    }
    
    DefaultListModel lstResourcePacksModel = new DefaultListModel(),
            lstTexturePacksModel = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddResourcePack;
    private javax.swing.JButton btnAddTexturePack;
    private javax.swing.JButton btnDeleteResourcePack;
    private javax.swing.JButton btnDeleteTexturePack;
    private javax.swing.JButton btnManageResourcePack;
    private javax.swing.JButton btnManageTexturePacks;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JList lstResourcePacks;
    private javax.swing.JList lstTexturePacks;
    // End of variables declaration//GEN-END:variables
}
