/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackhuang.hellominecraftlauncher.plugin.editpanels;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import org.jackhuang.hellominecraftlauncher.apis.utils.Compressor;
import org.jackhuang.hellominecraftlauncher.apis.utils.MessageBox;
import org.jackhuang.hellominecraftlauncher.apis.utils.Utils;
import org.jackhuang.hellominecraftlauncher.plugin.HMCLPlugin;
import org.jackhuang.hellominecraftlauncher.utilities.C;

/**
 *
 * @author hyh
 */
public class SaveWorldPanel extends javax.swing.JPanel {

    /**
     * Creates new form SaveWorldPanel
     */
    public SaveWorldPanel() {
        initComponents();
        
        setName(C.I18N.getString("WorldSaving"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstSavesBackup = new javax.swing.JList();
        btnBackupTo = new javax.swing.JButton();
        btnManageTexturePacks1 = new javax.swing.JButton();

        setName(""); // NOI18N

        jScrollPane7.setViewportView(lstSavesBackup);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jackhuang/hellominecraftlauncher/I18N"); // NOI18N
        btnBackupTo.setText(bundle.getString("备份到")); // NOI18N
        btnBackupTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupToActionPerformed(evt);
            }
        });

        btnManageTexturePacks1.setText(bundle.getString("管理")); // NOI18N
        btnManageTexturePacks1.setToolTipText("打开资源管理器");
        btnManageTexturePacks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTexturePacks1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBackupTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageTexturePacks1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnManageTexturePacks1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackupTo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackupToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupToActionPerformed
        String str = (String) lstSavesBackup.getSelectedValue();
        if (str == null) {
            return;
        }

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle(C.I18N.getString("保存压缩包到"));
        fc.setMultiSelectionEnabled(false);
        fc.setFileFilter(new ZipFileFilter());
        fc.setSelectedFile(new File(str + ".zip"));
        fc.showSaveDialog(this);
        try {
            String path = fc.getSelectedFile().getCanonicalPath();
            String path2 = getGameDir() + "saves" + File.separator + str;
            Compressor.zip(path2, path);
        } catch (IOException e) {
            MessageBox.Show(C.I18N.getString("保存失败"));
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBackupToActionPerformed

    private void btnManageTexturePacks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTexturePacks1ActionPerformed
        try {
            File f = new File(getGameDir() + "saves");
            f.mkdirs();
            java.awt.Desktop.getDesktop().open(f);
        } catch (Exception ex) {
            MessageBox.Show(C.I18N.getString("无法打开资源管理器: ") + ex.getMessage());
        }
    }//GEN-LAST:event_btnManageTexturePacks1ActionPerformed

    private String getGameDir() {
        return Utils.getGameDir(HMCLPlugin.env.getVersion(), HMCLPlugin.env.getDefaultGameDir());
    }

    class ZipFileFilter extends FileFilter {

        public String getDescription() {
            return "*.zip(*.zip)";
        }

        public boolean accept(File file) {
            String name = file.getName();
            return name.toLowerCase().endsWith(".zip");
        }
    }

    public void loadSaves() {
        String path = getGameDir() + "saves";
        File file = new File(path);
        lstSavesBackupModel.clear();
        lstSavesBackup.setModel(lstSavesBackupModel);
        if (!file.exists()) {
            return;
        }
        ArrayList<String> al = Utils.findAllDir(file);
        for (String s : al) {
            lstSavesBackupModel.addElement(s);
        }
        lstSavesBackup.updateUI();
    }
    
    DefaultListModel
            lstSavesBackupModel = new DefaultListModel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackupTo;
    private javax.swing.JButton btnManageTexturePacks1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList lstSavesBackup;
    // End of variables declaration//GEN-END:variables
}
