/*
 * Hello Minecraft! Launcher.
 * Copyright (C) 2013  huangyuhui <huanghongxun2008@126.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see {http://www.gnu.org/licenses/}.
 */
package org.jackhuang.hellominecraft.launcher.ui.modpack;

import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jackhuang.hellominecraft.util.C;
import org.jackhuang.hellominecraft.util.ui.wizard.spi.WizardController;

/**
 *
 * @author huangyuhui
 */
public class ModpackInitializationPanel extends javax.swing.JPanel {

    public static final String KEY_GAME_VERSION = "gameVersion";
    public static final String KEY_MODPACK_LOCATION = "modpackLocation";

    private final WizardController controller;
    private final Map wizardData;

    /**
     * Creates new form ModpackInitializationPanel
     */
    public ModpackInitializationPanel(WizardController controller, Map wizardData, String[] versions) {
        initComponents();

        this.controller = controller;
        this.wizardData = wizardData;
        wizardData.put(KEY_GAME_VERSION, versions);

        configureComboContents();
        controller.setProblem(C.i18n("modpack.not_a_valid_location"));
    }

    private void configureComboContents() {
        String[] versions = (String[]) wizardData.get(KEY_GAME_VERSION);
        cboGameVersion.setModel(new DefaultComboBoxModel<>(versions));
        if (versions.length > 0)
            wizardData.put(KEY_GAME_VERSION, versions[0]);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModpackLocation = new javax.swing.JLabel();
        txtModpackLocation = new javax.swing.JTextField();
        cboModpackLocation = new javax.swing.JButton();
        lblGameVersion = new javax.swing.JLabel();
        cboGameVersion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        lblModpackLocation.setText(C.i18n("modpack.save")); // NOI18N

        txtModpackLocation.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtModpackLocationCaretUpdate(evt);
            }
        });

        cboModpackLocation.setText("...");
        cboModpackLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModpackLocationActionPerformed(evt);
            }
        });

        lblGameVersion.setText("要导出的游戏版本");

        cboGameVersion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGameVersionItemStateChanged(evt);
            }
        });

        jLabel1.setText(C.i18n("modpack.warning")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModpackLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboModpackLocation))
                    .addComponent(txtModpackLocation)
                    .addComponent(cboGameVersion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGameVersion)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModpackLocation)
                    .addComponent(cboModpackLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModpackLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGameVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboGameVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboModpackLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModpackLocationActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle(C.i18n("modpack.save"));
        fc.setMultiSelectionEnabled(false);
        fc.setFileFilter(new FileNameExtensionFilter(C.i18n("modpack") + "(*.zip)", "zip"));
        fc.showSaveDialog(this);
        if (fc.getSelectedFile() != null)
            txtModpackLocation.setText(fc.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_cboModpackLocationActionPerformed

    private void txtModpackLocationCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtModpackLocationCaretUpdate
        wizardData.put(KEY_MODPACK_LOCATION, txtModpackLocation.getText());

        if (txtModpackLocation.getText().trim().isEmpty())
            controller.setProblem(C.i18n("modpack.not_a_valid_location"));
        else
            controller.setProblem(null);
    }//GEN-LAST:event_txtModpackLocationCaretUpdate

    private void cboGameVersionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGameVersionItemStateChanged
        wizardData.put(KEY_GAME_VERSION, cboGameVersion.getSelectedItem());
    }//GEN-LAST:event_cboGameVersionItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboGameVersion;
    private javax.swing.JButton cboModpackLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGameVersion;
    private javax.swing.JLabel lblModpackLocation;
    private javax.swing.JTextField txtModpackLocation;
    // End of variables declaration//GEN-END:variables
}
