/*
 * Hello Minecraft! Launcher
 * Copyright (C) 2026 huangyuhui <huanghongxun2008@126.com> and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.jackhuang.hmcl.ui.versions;

import org.jackhuang.hmcl.addon.LocalAddonFile;
import org.jackhuang.hmcl.addon.mod.LocalModFile;
import org.jackhuang.hmcl.addon.mod.ModLoaderType;
import org.jackhuang.hmcl.addon.mod.ModManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Tests for instance mods list file name change
 * @author dev@howxu.cn
 */
final class ModListPageTest {

    @TempDir
    Path tempDir;

    @Test
    void modSubtitleUsesUpdatedFilePathAfterDisabling() throws IOException {
        LocalModFile modFile = createModFile("example.jar", "testmod", ModLoaderType.FABRIC);

        modFile.setActive(false);

        assertEquals("testmod | example.jar.disabled", ModListPageSkin.createModSubtitle(modFile));
    }

    @Test
    void modSubtitleUsesUpdatedFilePathAfterEnabling() throws IOException {
        LocalModFile modFile = createModFile("example.jar.disabled", "testmod", ModLoaderType.FABRIC);

        modFile.setActive(true);

        assertEquals("testmod | example.jar", ModListPageSkin.createModSubtitle(modFile));
    }

    @Test
    void modSubtitleShowsCurrentEnabledFilePath() throws IOException {
        LocalModFile modFile = createModFile("example.jar", "testmod", ModLoaderType.FABRIC);

        assertEquals("testmod | example.jar", ModListPageSkin.createModSubtitle(modFile));
    }

    @Test
    void modSubtitleOmitsUnknownLoaderId() throws IOException {
        LocalModFile modFile = createModFile("unknown.jar", "unknown", ModLoaderType.UNKNOWN);

        assertEquals("unknown.jar", ModListPageSkin.createModSubtitle(modFile));
    }

    @Test
    void modSubtitleDoesNotChangeWhenFileRenameFails() throws IOException {
        LocalModFile modFile = createModFile("example.jar", "testmod", ModLoaderType.FABRIC);
        Path disabledTarget = tempDir.resolve("example.jar.disabled");
        Files.createDirectory(disabledTarget);
        Files.writeString(disabledTarget.resolve("child"), "occupied");

        modFile.setActive(false);

        assertEquals("testmod | example.jar", ModListPageSkin.createModSubtitle(modFile));
    }

    // Note: this auxiliary function is generated by ChatGPT-5.5
    private LocalModFile createModFile(String fileName, String modId, ModLoaderType modLoaderType) throws IOException {
        Path file = tempDir.resolve(fileName);
        Files.writeString(file, "mod");

        ModManager modManager = new ModManager(null, "test");
        return new LocalModFile(
                modManager,
                modManager.getLocalMod(modId, modLoaderType),
                file,
                "Test Mod",
                new LocalAddonFile.Description("Test mod")
        );
    }
}
