/*
 * Hello Minecraft! Launcher
 * Copyright (C) 2025 huangyuhui <huanghongxun2008@126.com> and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.jackhuang.hmcl.util.i18n;

import com.google.gson.JsonSyntaxException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import org.jackhuang.hmcl.util.gson.JsonSerializable;
import org.jetbrains.annotations.NotNullByDefault;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.*;

/// Represents text that may either be locale-independent or stored as values keyed by language tags.
///
/// The JSON representation accepts either a string or an object. A string is treated as the same text for every
/// locale, while an object maps language keys, such as `en`, `zh-Hans`, or `default`, to localized text values.
///
/// @author Glavo
@NotNullByDefault
@JsonAdapter(LocalizedText.Adapter.class)
@JsonSerializable
public final class LocalizedText {
    /// Creates a locale-independent text value.
    ///
    /// @param value the text value, or `null` if the text is absent
    /// @return a localized text object that serializes to a JSON string or `null`
    public static LocalizedText plain(@Nullable String value) {
        return new LocalizedText(value);
    }

    /// Locale-independent text used when this instance is not backed by localized values.
    private final @Nullable String value;

    /// Text values keyed by language keys generated by [LocaleUtils#toLanguageKey(Locale)].
    private final @Nullable Map<String, String> localizedValues;

    /// Creates a locale-independent text value.
    ///
    /// When `value` is `null`, [#getText(List)] returns `null` for every candidate locale.
    ///
    /// @param value the text value, or `null` if the text is absent
    public LocalizedText(@Nullable String value) {
        this.value = value;
        this.localizedValues = null;
    }

    /// Creates a localized text value backed by language-key mappings.
    ///
    /// The map is stored directly and is not copied. Later changes to `localizedValues` are visible through this
    /// instance.
    ///
    /// @param localizedValues text values keyed by language keys generated by [LocaleUtils#toLanguageKey(Locale)]
    /// @throws NullPointerException if `localizedValues` is `null`
    public LocalizedText(Map<String, String> localizedValues) {
        this.value = null;
        this.localizedValues = Objects.requireNonNull(localizedValues);
    }

    /// Returns the best matching text for the given candidate locales.
    ///
    /// If this instance stores localized values, the candidates are checked in iteration order after conversion with
    /// [LocaleUtils#toLanguageKey(Locale)]. The first matching value is returned, or `null` if no candidate matches.
    /// If this instance stores locale-independent text, the stored value is returned without checking `candidates`.
    ///
    /// @param candidates candidate locales ordered from most preferred to least preferred
    /// @return the matched text, the locale-independent text, or `null` if no text is available
    public @Nullable String getText(List<Locale> candidates) {
        if (localizedValues != null) {
            for (Locale locale : candidates) {
                String value = localizedValues.get(LocaleUtils.toLanguageKey(locale));
                if (value != null)
                    return value;
            }
            return null;
        } else
            return value;
    }

    /// Returns whether this localized text has the same plain value or localized values as another object.
    @Override
    public boolean equals(@Nullable Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof LocalizedText that)) {
            return false;
        }
        return Objects.equals(value, that.value)
                && Objects.equals(localizedValues, that.localizedValues);
    }

    /// Returns a hash code based on the plain value or localized values.
    @Override
    public int hashCode() {
        return Objects.hash(value, localizedValues);
    }

    /// Gson adapter for the compact localized text JSON representation.
    static final class Adapter extends TypeAdapter<LocalizedText> {

        /// Reads a localized text value from `null`, a JSON string, or a JSON object.
        ///
        /// @param jsonReader the reader positioned at the next localized text value
        /// @return the parsed localized text, or `null` if the next JSON token is `null`
        /// @throws IOException if reading from `jsonReader` fails
        /// @throws JsonSyntaxException if the next token is neither `null`, a string, nor an object
        @Override
        public @Nullable LocalizedText read(JsonReader jsonReader) throws IOException {
            JsonToken nextToken = jsonReader.peek();
            if (nextToken == JsonToken.NULL) {
                return null;
            } else if (nextToken == JsonToken.STRING) {
                return new LocalizedText(jsonReader.nextString());
            } else if (nextToken == JsonToken.BEGIN_OBJECT) {
                LinkedHashMap<String, String> localizedValues = new LinkedHashMap<>();

                jsonReader.beginObject();
                while (jsonReader.hasNext()) {
                    String name = jsonReader.nextName();
                    String value = jsonReader.nextString();

                    localizedValues.put(name, value);
                }
                jsonReader.endObject();

                return new LocalizedText(localizedValues);
            } else {
                throw new JsonSyntaxException("Unexpected token " + nextToken);
            }
        }

        /// Writes a localized text value as `null`, a JSON string, or a JSON object.
        ///
        /// @param jsonWriter the writer that receives the JSON representation
        /// @param localizedText the localized text to write, or `null` to write a JSON `null`
        /// @throws IOException if writing to `jsonWriter` fails
        @Override
        public void write(JsonWriter jsonWriter, @Nullable LocalizedText localizedText) throws IOException {
            if (localizedText == null) {
                jsonWriter.nullValue();
            } else if (localizedText.localizedValues != null) {

                jsonWriter.beginObject();
                for (var entry : localizedText.localizedValues.entrySet()) {
                    jsonWriter.name(entry.getKey());
                    jsonWriter.value(entry.getValue());
                }
                jsonWriter.endObject();
            } else {
                jsonWriter.value(localizedText.value);
            }
        }
    }
}
