/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackhuang.hellominecraftlauncher.apis;

import org.jackhuang.hellominecraftlauncher.apis.utils.SwingUtils;
import org.jackhuang.hellominecraftlauncher.download.DownloadAllThread;
import org.jackhuang.hellominecraftlauncher.download.DownloadListener;

/**
 *
 * @author hyh
 */
public class DownloadWindow extends javax.swing.JDialog
    implements DownloadListener, DoneListener<String, Integer> {
    
    boolean suc = false;

    DownloadAllThread dat;
    /**
     * Creates new form DownloadWindow
     */
    public DownloadWindow() {
        initComponents();

        SwingUtils.resetWindowLocation(this);
        
        setModal(true);
        
        dat = new DownloadAllThread(this);
        dat.addDoingListener(this);
        dat.addDoneListener(new DoneListener<String, Integer>() {

            @Override
            public void onDone(String value, Integer value2) {
                pgsTotal.setMaximum(dat.size());
                pgsTotal.setValue(pgsTotal.getValue() + 1);
            }
        });
    }
    
    public void addDownloadURL(String mark, String url, String location) {
        dat.addDownloadURL(mark, url, location);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        pgsSingle = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pgsTotal = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDownload = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("下载");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pgsSingle.setStringPainted(true);

        jLabel1.setText("单项进度");

        jLabel2.setText("总进度");

        pgsTotal.setStringPainted(true);

        txtDownload.setColumns(20);
        txtDownload.setRows(5);
        jScrollPane2.setViewportView(txtDownload);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(349, 349, 349))
                    .addComponent(pgsSingle, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pgsTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgsSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dat.start();
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dat.interrupt();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar pgsSingle;
    private javax.swing.JProgressBar pgsTotal;
    private javax.swing.JTextArea txtDownload;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnProgress(int progress, int max) {
        pgsSingle.setMaximum(max);
        pgsSingle.setValue(progress);
    }

    @Override
    public boolean OnFailed() {
        return true;
    }

    @Override
    public void OnDone() {
        suc = true;
        this.dispose();
    }

    @Override
    public void onDone(String value, Integer value2) {
        txtDownload.append("正在下载：" + value);
	SwingUtils.moveEnd(txtDownload);
    }
    
    public boolean isDownloadSuccessfully() {
        return suc;
    }

    @Override
    public void OnFailedMoreThan5Times(String value) {
        txtDownload.append("下载失败：" + value);
	SwingUtils.moveEnd(txtDownload);
    }
}
