name: Check Translations

on:
  push:
    paths:
      - '**.properties'
  pull_request:
    paths:
      - '**.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check style test
        run: ./gradlew checkTranslations --no-daemon
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
