name: Check Style

on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check style main
        run: ./gradlew checkstyleMain --no-daemon
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      - name: Check style test
        run: ./gradlew checkstyleTest --no-daemon
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
